### ISSUE TITLE
Printers are not available

### ISSUE THREAD

**Issue by rsanden** [snapcrafters/gimp#109]
This is a duplicate of https://github.com/snapcrafters/gimp/issues/22 .
However, I can't seem to re-open that issue. It's not fixed.
We should close this one and re-open that ticket.

**Comment by jasonp019** [comment]
I have the same issue on Ubuntu 20.10.  How is it that Linux has devolved to the point that its applications are no longer able to see and access the *system-defined* printers?!?  This wasn't an issue over two decades ago -- why is it happening now?

**Comment by diddledan** [comment]
The ability to use cups grants the gimp snap effective ownership of your computer. Because of this it is not automatically given this access level, allowing you to choose whether to grant the permission. You may opt into allowing cups access via running `sudo snap connect gimp:cups-control` or by using the Snap Store app to grant the permission via a gui.

**Comment by jasonp019** [comment]
What is you don't use *snap*?  If you don't use the snap system you can't access the printers provided by the system?

**Comment by diddledan** [comment]
If you don't use snap, then this is the wrong place to be. This repository and the issues here are about the gimp snap package.

**Comment by jasonp019** [comment]
You can thank Google's search for that.  However, I removed the snap version I had apparently unintentionally installed and went back to the apt-installed version and all worked as it should.
