### ISSUE TITLE
/media/XXXX permission denied

### ISSUE THREAD

**Issue by badandybrew** [snapcrafters/gimp#19]
Gimp is unable to access files outside of home.  I was able to remedy the error by changing the snap permissions by connecting the gimp snap to the removable-media plug.  Perheps the default snap permessions could be adjusted.

`snap connect gimp:removable-media :removable-media`

Best of Luck,

Andy

**Comment by omkarnathsingh** [comment]
Isn't that the default behavior of snap applications unless they are packed in classic confinement?

**Comment by diddledan** [comment]
I'm reluctant to request auto-connecting that interface because there is no hard requirement for gimp to have that level of access. Auto-connecting will merely be a convenience rather than a fix for brokenness. As you discovered, you can connect the interface yourself easily enough, and in at least Ubuntu 18.04 there is a UI in Gnome Software to enable you to connect and disconnect via point-and-click. Hopefully that will roll out to other distributions too, but that is up to their teams.

**Comment by ahundt** [comment]
What is the name of that UI to connect and disconnect via point and click?
