### ISSUE TITLE
Incorrect Snap package localisation

### ISSUE THREAD

**Issue by starmanmcmlxxxi** [snapcrafters/gimp#25]
In Ubuntu Bionic, the gimp Snap package installs only localised to english, despite the system I'm working on is set to spanish language. It seems there's no way to correct the issue after installation.

**Comment by diddledan** [comment]
Did you get the wrong repo (this issue tracker is for GIMP) or did you mistype GIMP as VLC? The described behaviour is also present GIMP, and has also been reported by others.

**Comment by starmanmcmlxxxi** [comment]
Sorry, it was a typo (vlc snap shows the same issue and I was reporting it). The issue is for the gimp snap package as described above (I've just edited the original report).

**Comment by diddledan** [comment]
Thanks for the confirmation, I didn't want you to be confused when we started talking about GIMP if you really meant to file it to VLC :-) This issue is a long-standing one, and I don't understand it yet. I think it might be a deficiency of snapd, but can't be sure I haven't screwed up the GIMP packaging. In a related problem it seems that [localisations are also ignored for folders in your home directory](https://forum.snapcraft.io/t/snap-does-not-respect-directory-settings/3274/19), which leads me to think localisations in general are broken across the board.

**Comment by starmanmcmlxxxi** [comment]
Thank you for adressing this one! If it helps, Mozilla Firefox, Musescore and gnome-system-monitor snap packages are working fine under my localisation (maybe it's a packaging related issue).

**Comment by diddledan** [comment]
I think I've fixed it. Can you try:

```bash
$ sudo snap refresh --candidate gimp
```
Then run GIMP and see if the localisation/translation is working?

**Comment by starmanmcmlxxxi** [comment]
Yes! It's working really fine! Congratulations!
Please, let me know when I could reinstall the stable package when it's fixed.
Thank you!

**Comment by diddledan** [comment]
Closing as fixed then :-)
